void test() {
  assert_false(is_prime(0));
  assert_false(is_prime(1));
  assert_true(is_prime(2));
  assert_true(is_prime(3));
  assert_false(is_prime(4));
  assert_true(is_prime(5));
  assert_false(is_prime(6));
  assert_true(is_prime(7));
  assert_false(is_prime(8));
  assert_false(is_prime(9));
  assert_false(is_prime(10));
  assert_true(is_prime(11));
  assert_false(is_prime(12));
  assert_true(is_prime(13));
  assert_false(is_prime(14));
  assert_false(is_prime(15));
  assert_false(is_prime(16));
  assert_true(is_prime(17));
  assert_false(is_prime(18));
  assert_true(is_prime(19));
  assert_false(is_prime(20));
  assert_false(is_prime(21));
  assert_false(is_prime(22));
  assert_true(is_prime(23));
  assert_false(is_prime(24));
  assert_false(is_prime(25));
  assert_false(is_prime(26));
  assert_false(is_prime(27));
  assert_false(is_prime(28));
  assert_true(is_prime(29));
  assert_false(is_prime(30));
  assert_true(is_prime(31));
  assert_false(is_prime(32));
}
// vim: cc=60 ts=2 sts=2 sw=2:
